# Generated by Django 5.2.4 on 2025-07-30 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_coupon_order_descount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='descount',
            new_name='discount',
        ),
    ]
